# Generated by Django 4.0.4 on 2022-06-29 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_contactanos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membresia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idMembresia', models.CharField(max_length=35, verbose_name='Nombre de la membresia')),
            ],
        ),
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=40)),
                ('idMembresia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.membresia')),
            ],
        ),
    ]
