# Generated by Django 4.0.4 on 2022-07-07 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_membresia_suscripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Seguimiento del Envio')),
            ],
        ),
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCli', models.CharField(max_length=50)),
                ('apellidoCli', models.CharField(max_length=50)),
                ('correoCli', models.EmailField(max_length=254)),
                ('telefonoCli', models.IntegerField()),
                ('SeguimientoCli', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.seguimiento')),
            ],
        ),
    ]
